Add support for LDAP authentication
stackabletech/nifi-operator pull request #303
Opened 2022-07-08 08:05 UTC by sbernauer

# Description

Add LDAP authentication.
Doesn't make to much sense without authZ, but that another story. Trying to split that to keep PRs small.

## Review Checklist

- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-07-11 09:24 UTC, maltesander requested changes
LGTM overall. One bigger thing, the `create_reporting_task_job` fails when using ldap:
```
cat: /stackable/adminuser/username: No such file or directory                                                   
cat: /stackable/adminuser/password: No such file or directory                                                   
usage: create_nifi_reporting_task.py [-h] -n NIFI_API_URL -u USERNAME -p                                        
                                     PASSWORD -v NIFI_VERSION -c CERT -m                                        
                                     METRICS_PORT [-t TASK_NAME]                                                
create_nifi_reporting_task.py: error: argument -u/--username: expected one argument
```
Not sure how, but it needs the right credentials from LDAP. Any idea how we can do that?

2022-07-12 06:22 UTC, sbernauer commented on rust/crd/Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
Nope, sadly not. I need https://github.com/stackabletech/operator-rs/commit/8c573874474d7f4b21719955844eb460d1f82d42

2022-07-20 06:49 UTC, sbernauer commented on rust/operator-binary/src/controller.rs
> +                client,
good point, implemented

2022-07-20 06:51 UTC, sbernauer commented
The reporting job should now be fixed.

2022-07-20 13:35 UTC, maltesander approved these changes
LGTM. Maybe talk to @siegfriedweber  how and when we can release a new operator-rs tag?

2022-07-27 14:08 UTC, sbernauer commented
@maltesander could you please do one final review?
I released operator-rs and tried using multiple LoginIdentityProviders without success (put the error in the description)

2022-07-28 12:12 UTC, maltesander approved these changes
LGTM.

2022-08-01 07:25 UTC, sbernauer commented
bors r+

2022-08-01 07:29 UTC, closed without merging