Enable logging
stackabletech/nifi-operator pull request #418
Opened 2023-01-26 18:24 UTC by maltesander

# Description

- enabled logging via logback

## Question

Collect logs from `create-reportin-task` (Job)?

fixes: https://github.com/stackabletech/nifi-operator/issues/415

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-01-27 17:37 UTC, maltesander commented
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/nifi-operator-it-custom/22/

2023-01-30 13:49 UTC, siegfriedweber requested changes
On the console, all logs are wrapped into another log entry:

```
2023-01-30 12:57:45,332 INFO [NiFi logging handler] org.apache.nifi.StdOut 2023-01-30 12:57:45,332 INFO [pool-9-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
```

In the log file, the console output is replicated:

```xml
<log4j:event logger="org.apache.nifi.controller.repository.WriteAheadFlowFileRepository"
             timestamp="1675083205329" level="INFO" thread="pool-9-thread-1">
  <log4j:message>Initiating checkpoint of FlowFile Repository</log4j:message>

</log4j:event>

<log4j:event logger="org.apache.nifi.StdOut"
             timestamp="1675083205329" level="INFO" thread="NiFi logging handler">
  <log4j:message>2023-01-30 12:53:25,329 INFO [pool-9-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository</log4j:message>

</log4j:event>
```

2023-01-30 13:49 UTC, siegfriedweber commented on tests/templates/kuttl/upgrade/02-install-nifi.yaml.j2
> +    vectorAggregatorConfigMapName: nifi-vector-aggregator-discovery
```suggestion
    vectorAggregatorConfigMapName: vector-aggregator-discovery
```

2023-01-30 13:49 UTC, siegfriedweber commented on tests/templates/kuttl/upgrade/05-upgrade-nifi.yaml.j2
> +    vectorAggregatorConfigMapName: nifi-vector-aggregator-discovery
```suggestion
    vectorAggregatorConfigMapName: vector-aggregator-discovery
```

2023-02-01 12:58 UTC, maltesander commented
Last test hopefully: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/nifi-operator-it-custom/23/

2023-02-01 13:13 UTC, siegfriedweber approved these changes
LGTM

2023-02-01 16:12 UTC, closed without merging